### PR TITLE
Restructuring

### PR DESCRIPTION
**Pull request by guFalcon**
- Did some changes to the inheritance structure.
  -- Made the baseobject inherit from MonoGames IDrawableComponent.
  That change should be up for debate.
- Added up- and down-movement.
  -- Thought that that should be possible to a limited extent.
- Constrained movement to viewport.
- Changed keyMap to sport diagonal movement.
- BaseGameObject now gets the spriteBatch from the game.

### CODE REVIEW

**Comment by guFalcon** [comment]
The question I have is:

Do we honor the 'old' way of organizing object-loading and unloading, updating, etc... like in XNA via the IDrawableGameComponent interface... You'd add the plane to the components-list of the game and it automatically gets updated, drawn, unloaded, etc...
That implicates that we have 'screens' and the game-screen is different from the settings-screen and gets loaded after you select the 'play' menu entry or something like that. The game-screen would then load all assets in the initialize-phase and unload them again when exited to get back to the settings-screen, or something like that.

Or should we implement our own such structure using the MG.EX interface-markers and our own. Then we'd have to call update, draw, initialize, etc... manually (which then results in the IMHO ugly switch blocks).

**Review by KuzDeveloper — APPROVED** [review]
Seems legit.

**Comment by guFalcon** [comment]
_lol_

That was a question.

:)

**Comment by nelzkie** [comment]
The old way seems tried and tested :D

**Comment by guFalcon** [comment]
Has anyone done it using only MG.EX without IDrawableGameComponent? I haven't.

**Comment by nelzkie** [comment]
Hmm i havent.

**Comment by Jjagg** [comment]
I dislike both, but it's a matter of preference really. I'd rather not abstract up to just update and draw.

**Comment by guFalcon** [comment]
Hmmm I see. I can second that.
But I only used the 'old' style and I came to like the LoadContent, Initialize and UnloadContent phases.
At first it seemed counter-intuitive, but after a while I saw why those are there :)
(They say that you don't value the UnloadContent method until you've realized how stupid the garbage-collector was ;) )

**Comment by Jjagg** [comment]
I usually still follow the same conventions by having functions called LoadContent, Initialize and so on, but I don't have an abstract base class GameObject that defines these methods. I also like to deviate a bit from the expected function declaration in some classes, e.g. to pass a spritebatch in a draw call.

> They say that you don't value the UnloadContent method until you've realized how stupid the garbage-collector was

Well, they have a different purpose. The garbage collector releases managed resources while you should release unmanaged resources yourself e.g. in an UnloadContent function :)

**Comment by guFalcon** [comment]
Hmmm. I think I'll take a look at the MG.EX examples for guidance.
And yeah, the thing about Unload() is true, but I always use it to help cleaning up, like unreferencing dependency cycles or eventhandlers and such. Helped a lot getting rid of mem-leaks.
Maybe those originally came from design-errors, but then I couldn't find them.
So unreferencing stuff helped a lot.
But, as I said, you're right. So I'm removing that code now. Should work.

**Pull request merged**
